In [151]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [152]:
path = '../data/final_data2.xlsx'
df = pd.read_excel(path)
df.head(25)

,Type of Degree,Department,Honor Grade of Degree,Job title,Type of employment,Sector,Date of current appointment,Monthly Salary (Rs-),From_Newspaper,From_Gazette,...,Reading_Other,English_Oral,English_Written,Student Associations,Organizing Workshops & Seminars,Charities,Sports,Cultural Activities,Other,Award/Achievement
0,Joint Major,ELTN,Second Lower,Infrastructure Network Engineer,Contract Basis,Private,2017-07-10 00:00:00,60000.0,0,0,...,0,Average,Average,1,1,1,1,1,1,1s Place ...
1,Joint Major,MMST,Second Lower,Operations Assistant Manager,Permanent,Private,2017-07-03 00:00:00,40000.0,0,0,...,0,Good,Good,1,1,1,1,1,1,University Colors
2,Joint Major,ELTN,Pass,Technical Officer,Permanent,Private,2017-04-24 00:00:00,30000.0,0,0,...,0,Good,Good,1,1,0,0,1,0,NaN
3,Joint Major,CMIS,Second Lower,Software Engineer,Permanent,Private,2017-02-04 00:00:00,40000.0,0,0,...,0,Average,Average,1,1,0,1,1,0,NaN
4,Joint Major,ELTN,Pass,Customer support Engineer,Permanent,Private,2017-03-13 00:00:00,30000.0,0,0,...,0,Good,Good,0,0,0,1,0,0,NaN
5,Joint Major,ELTN,Pass,IT Executive,Permanent,Private,2017-04-17 00:00:00,30000.0,0,0,...,0,Good,Good,0,0,0,1,0,0,NaN
6,Joint Major,ELTN,Pass,IT Executive,Permanent,Private,NaN,45000.0,0,0,...,0,Average,Good,0,1,1,1,1,0,NaN
7,Joint Major,ELTN,Pass,Electronic Engineer,Permanent,Private,2017-05-12 00:00:00,NaN,0,0,...,0,Good,Good,1,1,1,0,1,1,NaN
8,Special,IMGT,Pass,Production Executive,Training,Private,2017-06-01 00:00:00,40000.0,0,0,...,0,Good,Very Good,1,1,1,1,1,0,NaN
9,Joint Major,CMIS,Pass,Demonstrator,Temporary,Government,2017-03-27 00:00:00,39720.0,0,0,...,0,Good,Good,1,0,1,1,1,1,NaN
10,Special,MMST,Second Upper,Tutor,Temporary,Government,NaN,NaN,0,0,...,0,Average,Average,1,1,1,0,1,1,NaN
11,Joint Major,IMGT,Pass,Coordinator,Contract Basis,Semi Government,NaN,35000.0,0,0,...,0,Good,Very Good,1,1,1,0,1,1,NaN
12,Joint Major,ELTN,Second Lower,Demonstrator,Temporary,Government,2017-06-01 00:00:00,40000.0,0,1,...,1,Average,Average,1,1,0,1,1,0,NaN
13,Joint Major,CMIS,Second Upper,Software Engineer,Permanent,Private,2017-02-06 00:00:00,70000.0,0,0,...,0,Good,Good,1,1,1,1,1,1,Faculty Awards-2016
14,Joint Major,CMIS,Second Lower,Software Engineer,Permanent,Private,2017-02-06 00:00:00,70000.0,0,0,...,0,Average,Good,1,1,1,1,1,1,Faculty Award-2017
15,Special,ELTN,Second Upper,Demonstrator,Temporary,Government,NaN,39720.0,0,0,...,0,Average,Good,1,1,1,1,1,1,NaN
16,Joint Major,ELTN,Second Lower,Demonstrator,Temporary,Government,NaN,39720.0,0,0,...,0,Average,Good,1,1,1,0,1,0,NaN
17,Joint Major,CMIS,Second Lower,software developer,Permanent,Private,NaN,25000.0,0,0,...,0,Good,Good,1,1,1,0,1,0,NaN
18,Joint Major,ELTN,Second Lower,Demonstrator,Temporary,Semi Government,NaN,NaN,0,0,...,0,Average,Average,1,1,1,1,1,0,NaN
19,Joint Major,IMGT,Pass,Tutor,Temporary,Government,NaN,39720.0,0,0,...,0,Good,Good,1,1,1,1,1,1,NaN
20,Special,IMGT,Second Upper,Tutor,Temporary,Government,NaN,39720.0,0,0,...,0,Good,Good,1,1,1,1,1,0,NaN
21,Special,IMGT,Pass,Research Assistant,Temporary,Government,2017-05-01 00:00:00,50000.0,0,0,...,0,Good,Good,1,1,1,1,1,0,NaN
22,Joint Major,CMIS,Second Lower,Demonstrator,Temporary,Government,2017-03-07 00:00:00,39720.0,0,0,...,0,Very Good,Good,1,1,1,1,1,0,NaN
23,Joint Major,CMIS,Second Upper,Demonstrator,Temporary,Semi Government,2017-03-01 00:00:00,39720.0,0,0,...,0,Very Good,Good,1,0,0,1,1,0,NaN
24,Special,IMGT,Second Lower,Management trainee,Training,Private,NaN,15000.0,0,0,...,0,Good,Good,1,1,1,1,1,0,NaN

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 61 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Type of Degree                                                  362 non-null    object
 1   Department                                                      362 non-null    object
 2   Honor Grade of Degree                                           362 non-null    object
 3   Job title                                                       362 non-null    object
 4   Type of employment                                              362 non-null    object
 5   Sector                                                          362 non-null    object
 6   Date of current appointment                                     282 non-null    object
 7   Monthly Salary (Rs-)                                            307 non-null    float64
 8   From_Newspaper                                                  362 non-null    int64
 9   From_Gazette                                                    362 non-null    int64
 10  From_Online                                                     362 non-null    int64
 11  From_personal contacts                                          362 non-null    int64
 12  From_Competitive exam                                           362 non-null    int64
 13  From_Via internship (training)                                  362 non-null    int64
 14  From_Via university                                             362 non-null    int64
 15  From_Job fair/Career Guidance                                   362 non-null    int64
 16  From_Continuing with same job held during university education  362 non-null    int64
 17  From_Other                                                      362 non-null    int64
 18  Factor_Degree                                                   362 non-null    int64
 19  Factor_Class of degree                                          362 non-null    int64
 20  Factor_University Project                                       362 non-null    int64
 21  Factor_Reputation of university                                 362 non-null    int64
 22  Factor_Field of study                                           362 non-null    int64
 23  Factor_Research experience                                      362 non-null    int64
 24  Factor_Personal contacts                                        362 non-null    int64
 25  Factor_Previous work experience                                 362 non-null    int64
 26  Factor_English proficiency                                      362 non-null    int64
 27  Factor_Other professional qualifications                        362 non-null    int64
 28  Factor_Soft skills                                              362 non-null    int64
 29  Factor_Computer literacy                                        362 non-null    int64
 30  Factor_Other                                                    362 non-null    int64
 31  Additional qualifications                                       362 non-null    int64
 32  Completed_Diploma                                               362 non-null    int64
 33  Completed_M-Sc-                                                 362 non-null    int64
 34  Completed_M-Phil-                                               362 non-null    int64
 35  Completed_MBA                                                   362 non-null    int64
 36  Completed_Ph-D-                                                 362 non-null    int64
 37  Completed_LL-B-                                                 362 non-null    int64
 38  Completed_CIMA                                                  362 non-null    int64
 39  Completed_Chartered Accountancy                                 362 non-null    int64
 40  Completed_CMA                                                   362 non-null    int64
 41  Completed_Other                                                 362 non-null    int64
 42  Reading_Diploma                                                 362 non-null    int64
 43  Reading_M-Sc-                                                   362 non-null    int64
 44  Reading_M-Phil-                                                 362 non-null    int64
 45  Reading_MBA                                                     362 non-null    int64
 46  Reading_Ph-D-                                                   362 non-null    int64
 47  Reading_LL-B-                                                   362 non-null    int64
 48  Reading_CIMA                                                    362 non-null    int64
 49  Reading_Chartered Accountancy                                   362 non-null    int64
 50  Reading_CMA                                                     362 non-null    int64
 51  Reading_Other                                                   362 non-null    int64
 52  English_Oral                                                    362 non-null    object
 53  English_Written                                                 362 non-null    object
 54  Student Associations                                            362 non-null    int64
 55  Organizing Workshops & Seminars                                 362 non-null    int64
 56  Charities                                                       362 non-null    int64
 57  Sports                                                          362 non-null    int64
 58  Cultural Activities                                             362 non-null    int64
 59  Other                                                           362 non-null    int64
 60  Award/Achievement                                               71 non-null     object
dtypes: float64(1), int64(50), object(10)
memory usage: 172.6+ KB

In [154]:
df['English_Oral'].unique()

array(['Average', 'Good', 'Very Good', 'Poor', 'Excellent'], dtype=object)

In [155]:
df['English_Written'].unique()

array(['Average', 'Good', 'Very Good', 'Poor', 'Excellent'], dtype=object)

Ordinal Encoding

In [156]:
category_mapping = {'Poor': 0, 'Average': 1, 'Good': 2, 'Very Good': 3, 'Excellent': 4}
df['English_Oral'] = df['English_Oral'].map(category_mapping)
df['English_Written'] = df['English_Written'].map(category_mapping)
df.head()

,Type of Degree,Department,Honor Grade of Degree,Job title,Type of employment,Sector,Date of current appointment,Monthly Salary (Rs-),From_Newspaper,From_Gazette,...,Reading_Other,English_Oral,English_Written,Student Associations,Organizing Workshops & Seminars,Charities,Sports,Cultural Activities,Other,Award/Achievement
0,Joint Major,ELTN,Second Lower,Infrastructure Network Engineer,Contract Basis,Private,2017-07-10 00:00:00,60000.0,0,0,...,0,1,1,1,1,1,1,1,1,1s Place ...
1,Joint Major,MMST,Second Lower,Operations Assistant Manager,Permanent,Private,2017-07-03 00:00:00,40000.0,0,0,...,0,2,2,1,1,1,1,1,1,University Colors
2,Joint Major,ELTN,Pass,Technical Officer,Permanent,Private,2017-04-24 00:00:00,30000.0,0,0,...,0,2,2,1,1,0,0,1,0,NaN
3,Joint Major,CMIS,Second Lower,Software Engineer,Permanent,Private,2017-02-04 00:00:00,40000.0,0,0,...,0,1,1,1,1,0,1,1,0,NaN
4,Joint Major,ELTN,Pass,Customer support Engineer,Permanent,Private,2017-03-13 00:00:00,30000.0,0,0,...,0,2,2,0,0,0,1,0,0,NaN

In [157]:
# Convert to lowercase
df['Job title'] = df['Job title'].str.lower()

# Remove special characters
df['Job title'] = df['Job title'].str.replace(r'[^\w\s]', ' ', regex=True)

# Replace multiple spaces with a single space
df['Job title'] = df['Job title'].str.replace(r'\s+', ' ', regex=True)

# Strip leading and trailing spaces
df['Job title'] = df['Job title'].str.strip()

In [158]:
df.head()

,Type of Degree,Department,Honor Grade of Degree,Job title,Type of employment,Sector,Date of current appointment,Monthly Salary (Rs-),From_Newspaper,From_Gazette,...,Reading_Other,English_Oral,English_Written,Student Associations,Organizing Workshops & Seminars,Charities,Sports,Cultural Activities,Other,Award/Achievement
0,Joint Major,ELTN,Second Lower,infrastructure network engineer,Contract Basis,Private,2017-07-10 00:00:00,60000.0,0,0,...,0,1,1,1,1,1,1,1,1,1s Place ...
1,Joint Major,MMST,Second Lower,operations assistant manager,Permanent,Private,2017-07-03 00:00:00,40000.0,0,0,...,0,2,2,1,1,1,1,1,1,University Colors
2,Joint Major,ELTN,Pass,technical officer,Permanent,Private,2017-04-24 00:00:00,30000.0,0,0,...,0,2,2,1,1,0,0,1,0,NaN
3,Joint Major,CMIS,Second Lower,software engineer,Permanent,Private,2017-02-04 00:00:00,40000.0,0,0,...,0,1,1,1,1,0,1,1,0,NaN
4,Joint Major,ELTN,Pass,customer support engineer,Permanent,Private,2017-03-13 00:00:00,30000.0,0,0,...,0,2,2,0,0,0,1,0,0,NaN

In [159]:
# Preprocess job titles: Remove unnecessary characters like '-' and extra spaces
df['Job title'] = df['Job title'].str.replace('-', ' ', regex=False).str.strip()

In [160]:
df['Job title'].unique()
len(df['Job title'].unique())

163

In [161]:
# from sentence_transformers import SentenceTransformer
# from sklearn.cluster import AgglomerativeClustering

# # Load a pre-trained model for embeddings
# model = SentenceTransformer('all-MiniLM-L6-v2')

# # Generate embeddings for job titles
# unique_titles = df['Job title'].unique()
# embeddings = model.encode(unique_titles)

# # Cluster job titles
# clustering = AgglomerativeClustering(n_clusters=None, distance_threshold=1.5)
# clusters = clustering.fit_predict(embeddings)

# # Map job titles to clusters
# cluster_mapping = dict(zip(unique_titles, clusters))
# df['Job Cluster'] = df['Job title'].map(cluster_mapping)

# # Map clusters to representative job titles
# cluster_representative = df.groupby('Job Cluster')['Job title'].apply(lambda x: x.mode()[0])
# df['Job title'] = df['Job Cluster'].map(cluster_representative)

# # Display both Job title and Job title2 as a separate DataFrame
# df_titles = df[['Job title', 'Job title']]
# print(df_titles.head(30))

In [162]:
print(df['Job title'].unique())

['infrastructure network engineer' 'operations assistant manager'
 'technical officer' 'software engineer' 'customer support engineer'
 'it executive' 'electronic engineer' 'production executive'
 'demonstrator' 'tutor' 'coordinator' 'software developer'
 'research assistant' 'management trainee' 'associate system engineer'
 'industrial engineer' 'production coordinator' 'compliance officer'
 'management assistant' 'teacher' 'product data management engineer'
 'lean executive' 'human resources executive' 'in plant trainee'
 'accountant executive' 'site engineer' 'associate electronics engineer'
 'trainee staff assistant' 'planning executive'
 'test development engineer' 'work study officer'
 'assistant administration executive' 'associate software engineer'
 'electronics engineer' 'web developer' 'data analyst' 'business analyst'
 'sales administration support' 'planning coordinator'
 'purchasing officer' 'sales admin support' 'planning officer'
 'merchandising assistant' 'customer engagement specialist'
 'executive banking operation' 'deputy analyst' 'intern software engineer'
 'lecturer' 'assistant planning' 'merchandising executive'
 'staff assistant' 'process improvements executive' 'project executive'
 'project coordinator site engineer' 'junior software developer'
 'inspector of customs' 'assistant engineer'
 'executive operation research' 'executive work study' 'odoo development'
 'assistant supervisor' 'quality assurance technologist'
 'digital marketing analyst' 'executive bulk merchandiser'
 'executive he finance' 'data engineer' 'retail executive'
 'exeuctive bulk merchandiser' 'statistical programmer'
 'junior executive process' 'consultant'
 'software quality assurance engineer'
 'associate quality assurance engineer' 'staff officer'
 'supply chain analyst' 'lab assistant' 'sales and administration'
 'executive qa' 'associate engineer' 'devops engineer'
 'marketing executive' 'quality executive' 'seo specialist'
 'executive project coordinator' 'merchandiser bulk' 'puchasing executive'
 'operations analyst' 'senior site reliability engineer'
 'management service officer' 'production exceative'
 'sap technical consultant' 'junior test engineer' 'assistant manager'
 'product analyst' 'production control unit executive'
 'train controlling technical assistant' 'opertions analyst'
 'assistance electronic engineer' 'priduct develoment engineer'
 'trainee service engineeer' 'junior qulity assurance engineer'
 'work study assistant' 'associate it support' 'senior executive'
 'associate data engineer' 'associate quality assouance engineer'
 'operation analyst' 'qa engineer' 'biomedical service technical'
 'executive supply chain' 'system coordinator' 'engineering assistant'
 'recp technologist' 'regional accuracy analyst' 'executive sales'
 'associate web develpoer' 'assistant application analyst'
 'trainee seo specialist'
 'junior executive advance analytics data translator'
 'technical executive' 'engineer executive' 'associate operations analyst'
 'executire bulk merchenclder' 'operations analysist'
 'junior it executive' 'ui ux engineer intern' 'it administrator'
 'price analyst' 'intern business analyst' 'logistic analyst'
 'assistant customer stratesy planning' 'merchandising planning'
 'intern infrastructure operations' 'intern quality engineering'
 'administrive and operations assistant'
 'intern software quality engineer' 'intern business anylyst' 'hr officer'
 'material analyst' 'finance executive' 'assistant management accountant'
 'ux designer' 'procument executive' 'accounts assistant'
 'executive sourching' 'associate support engineer'
 'associate business analyst' 'machine learning engineer'
 'business application support' 'business analyst intern'
 'intern data engineer' 'product executive' 'assistant data analyst'
 'consultant assistant' 'junior software engineer'
 'quality assurance analyst' 'senior operations analyst' 'analyst'
 'junior quality assurance engineer' 'associate business analysis'
 'software qa engineer' 'assistant lecturer'
 'associate application support engineer']

In [163]:
from sentence_transformers import SentenceTransformer, util

# Step 1: Load the pre-trained model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Step 2: Define refined categories and their representative keywords
categories = {
    "Software Development": [
        "software engineer", "software developer", "junior software developer",
        "associate software engineer", "intern software engineer", "trainee software engineer",
        "web developer", "developer", "devops", "qa engineer", "quality assurance",
        "quality assurance engineer", "test engineer", "test analyst", "ui", "ux", "ui ux"
    ],
    "Data & Analytics": [
        "data analyst", "data engineer", "business analyst",
        "deputy analyst", "senior operations analyst", "analyst",
        "associate business analysis", "machine learning"
    ],
    "Engineering": [
        "engineer", "engineering", "technical officer",
        "infrastructure network engineer", "industrial engineering",
        "associate system engineer", "associate electronics engineer",
        "assistant engineer", "site engineer", "electronics engineer",
        "electronic engineer", "product data management engineer",
        "work study officer", "engineering executive", "project coordinator site engineer"
    ],
    "Marketing & Sales": [
        "marketing", "sales", "seo", "merchandising", 
        "merchandising assistant", "front end product development merchandising executive",
        "sales admin support", "sales administration support",
        "customer engagement specialist"
    ],
    "Human Resources": [
        "management trainee", "executive hr",
        "human resources executive", "hr"
    ],
    "Education & Research": [
        "tutor", "lecturer", "assistant lecturer",
        "demonstrator", "temporary demonstration", "teacher",
        "research assistant", "instructor"
    ],
    "Operations & Support": [
        "operations", "operations assistant manager",
        "customer support", "support engineer",
        "associate application support engineer",
        "coordinator", "planning coordinator", "project executive",
        "planning executive", "planning officer", "assistant planning",
        "executive planning", "production coordinator",
        "production executive", "lean executive",
        "assistant administration executive", "staff assistant",
        "trainee staff assistant", "management assistant",
        "executive banking operation", "compliance officer",
        "executive process improvements", "executive", "operations analyst"
    ],
    "Finance & Accounting": [
        "finance", "accountant executive", "account", "inspector of customs",
        "purchasing officer"
    ]
}

# Step 3: Compute category embeddings
category_embeddings = {
    category: model.encode(keywords) for category, keywords in categories.items()
}

# Step 4: Function to classify job titles
def classify_job_title(job_title):
    job_embedding = model.encode(job_title)
    best_category = None
    max_similarity = -1

    for category, embeddings in category_embeddings.items():
        similarity = max(util.cos_sim(job_embedding, embedding).item() for embedding in embeddings)
        if similarity > max_similarity:
            max_similarity = similarity
            best_category = category

    return best_category

# Step 5: Apply classification to each row and create a new column
df['category'] = df['Job title'].map(classify_job_title)

In [164]:
df.head()

,Type of Degree,Department,Honor Grade of Degree,Job title,Type of employment,Sector,Date of current appointment,Monthly Salary (Rs-),From_Newspaper,From_Gazette,...,English_Oral,English_Written,Student Associations,Organizing Workshops & Seminars,Charities,Sports,Cultural Activities,Other,Award/Achievement,category
0,Joint Major,ELTN,Second Lower,infrastructure network engineer,Contract Basis,Private,2017-07-10 00:00:00,60000.0,0,0,...,1,1,1,1,1,1,1,1,1s Place ...,Engineering
1,Joint Major,MMST,Second Lower,operations assistant manager,Permanent,Private,2017-07-03 00:00:00,40000.0,0,0,...,2,2,1,1,1,1,1,1,University Colors,Operations & Support
2,Joint Major,ELTN,Pass,technical officer,Permanent,Private,2017-04-24 00:00:00,30000.0,0,0,...,2,2,1,1,0,0,1,0,NaN,Engineering
3,Joint Major,CMIS,Second Lower,software engineer,Permanent,Private,2017-02-04 00:00:00,40000.0,0,0,...,1,1,1,1,0,1,1,0,NaN,Software Development
4,Joint Major,ELTN,Pass,customer support engineer,Permanent,Private,2017-03-13 00:00:00,30000.0,0,0,...,2,2,0,0,0,1,0,0,NaN,Operations & Support

In [165]:
print(len(df['Job title'].unique()))

163

In [166]:
df['Job title'].unique()

array(['infrastructure network engineer', 'operations assistant manager',
       'technical officer', 'software engineer',
       'customer support engineer', 'it executive', 'electronic engineer',
       'production executive', 'demonstrator', 'tutor', 'coordinator',
       'software developer', 'research assistant', 'management trainee',
       'associate system engineer', 'industrial engineer',
       'production coordinator', 'compliance officer',
       'management assistant', 'teacher',
       'product data management engineer', 'lean executive',
       'human resources executive', 'in plant trainee',
       'accountant executive', 'site engineer',
       'associate electronics engineer', 'trainee staff assistant',
       'planning executive', 'test development engineer',
       'work study officer', 'assistant administration executive',
       'associate software engineer', 'electronics engineer',
       'web developer', 'data analyst', 'business analyst',
       'sales administration support', 'planning coordinator',
       'purchasing officer', 'sales admin support', 'planning officer',
       'merchandising assistant', 'customer engagement specialist',
       'executive banking operation', 'deputy analyst',
       'intern software engineer', 'lecturer', 'assistant planning',
       'merchandising executive', 'staff assistant',
       'process improvements executive', 'project executive',
       'project coordinator site engineer', 'junior software developer',
       'inspector of customs', 'assistant engineer',
       'executive operation research', 'executive work study',
       'odoo development', 'assistant supervisor',
       'quality assurance technologist', 'digital marketing analyst',
       'executive bulk merchandiser', 'executive he finance',
       'data engineer', 'retail executive', 'exeuctive bulk merchandiser',
       'statistical programmer', 'junior executive process', 'consultant',
       'software quality assurance engineer',
       'associate quality assurance engineer', 'staff officer',
       'supply chain analyst', 'lab assistant',
       'sales and administration', 'executive qa', 'associate engineer',
       'devops engineer', 'marketing executive', 'quality executive',
       'seo specialist', 'executive project coordinator',
       'merchandiser bulk', 'puchasing executive', 'operations analyst',
       'senior site reliability engineer', 'management service officer',
       'production exceative', 'sap technical consultant',
       'junior test engineer', 'assistant manager', 'product analyst',
       'production control unit executive',
       'train controlling technical assistant', 'opertions analyst',
       'assistance electronic engineer', 'priduct develoment engineer',
       'trainee service engineeer', 'junior qulity assurance engineer',
       'work study assistant', 'associate it support', 'senior executive',
       'associate data engineer', 'associate quality assouance engineer',
       'operation analyst', 'qa engineer', 'biomedical service technical',
       'executive supply chain', 'system coordinator',
       'engineering assistant', 'recp technologist',
       'regional accuracy analyst', 'executive sales',
       'associate web develpoer', 'assistant application analyst',
       'trainee seo specialist',
       'junior executive advance analytics data translator',
       'technical executive', 'engineer executive',
       'associate operations analyst', 'executire bulk merchenclder',
       'operations analysist', 'junior it executive',
       'ui ux engineer intern', 'it administrator', 'price analyst',
       'intern business analyst', 'logistic analyst',
       'assistant customer stratesy planning', 'merchandising planning',
       'intern infrastructure operations', 'intern quality engineering',
       'administrive and operations assistant',
       'intern software quality engineer', 'intern business anylyst',
       'hr officer', 'material analyst', 'finance executive',
       'assistant management accountant', 'ux designer',
       'procument executive', 'accounts assistant', 'executive sourching',
       'associate support engineer', 'associate business analyst',
       'machine learning engineer', 'business application support',
       'business analyst intern', 'intern data engineer',
       'product executive', 'assistant data analyst',
       'consultant assistant', 'junior software engineer',
       'quality assurance analyst', 'senior operations analyst',
       'analyst', 'junior quality assurance engineer',
       'associate business analysis', 'software qa engineer',
       'assistant lecturer', 'associate application support engineer'],
      dtype=object)

Zero-Shot Classification

In [167]:
# from transformers import pipeline

# # Define your candidate categories
# candidate_labels = [
#     "Software Engineering", "Data Science", "Data Analyst", "Marketing", "Finance", "Human Resources",
#     "Product Management", "Customer Support", "Sales", "Design", "Operations"
# ]


# # Initialize zero-shot classification pipeline
# classifier = pipeline("zero-shot-classification", model="joeddav/xlm-roberta-large-xnli")

# # Get unique job titles
# unique_titles = df['Job title'].unique()

# # Classify each job title
# title_to_category = {}
# for title in unique_titles:
#     result = classifier(title, candidate_labels)
#     best_label = result['labels'][0]  # Top predicted category
#     title_to_category[title] = best_label

# # Map results back to the DataFrame
# df['Job Category'] = df['Job title'].map(title_to_category)

# # Display original and categorized titles
# df_titles = df[['Job title', 'Job Category']]
# print(df_titles.head())

In [168]:
df.head()

,Type of Degree,Department,Honor Grade of Degree,Job title,Type of employment,Sector,Date of current appointment,Monthly Salary (Rs-),From_Newspaper,From_Gazette,...,English_Oral,English_Written,Student Associations,Organizing Workshops & Seminars,Charities,Sports,Cultural Activities,Other,Award/Achievement,category
0,Joint Major,ELTN,Second Lower,infrastructure network engineer,Contract Basis,Private,2017-07-10 00:00:00,60000.0,0,0,...,1,1,1,1,1,1,1,1,1s Place ...,Engineering
1,Joint Major,MMST,Second Lower,operations assistant manager,Permanent,Private,2017-07-03 00:00:00,40000.0,0,0,...,2,2,1,1,1,1,1,1,University Colors,Operations & Support
2,Joint Major,ELTN,Pass,technical officer,Permanent,Private,2017-04-24 00:00:00,30000.0,0,0,...,2,2,1,1,0,0,1,0,NaN,Engineering
3,Joint Major,CMIS,Second Lower,software engineer,Permanent,Private,2017-02-04 00:00:00,40000.0,0,0,...,1,1,1,1,0,1,1,0,NaN,Software Development
4,Joint Major,ELTN,Pass,customer support engineer,Permanent,Private,2017-03-13 00:00:00,30000.0,0,0,...,2,2,0,0,0,1,0,0,NaN,Operations & Support

In [169]:
df['Date of current appointment '] = pd.to_datetime(df['Date of current appointment '], format="%Y-%m", errors='coerce').dt.to_period('M')

In [170]:
df['Date of current appointment '].dtype

period[M]

In [171]:
df = df.iloc[:,0:62]

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 62 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Type of Degree                                                  362 non-null    object
 1   Department                                                      362 non-null    object
 2   Honor Grade of Degree                                           362 non-null    object
 3   Job title                                                       362 non-null    object
 4   Type of employment                                              362 non-null    object
 5   Sector                                                          362 non-null    object
 6   Date of current appointment                                     281 non-null    period[M]
 7   Monthly Salary (Rs-)                                            307 non-null    float64
 8   From_Newspaper                                                  362 non-null    int64
 9   From_Gazette                                                    362 non-null    int64
 10  From_Online                                                     362 non-null    int64
 11  From_personal contacts                                          362 non-null    int64
 12  From_Competitive exam                                           362 non-null    int64
 13  From_Via internship (training)                                  362 non-null    int64
 14  From_Via university                                             362 non-null    int64
 15  From_Job fair/Career Guidance                                   362 non-null    int64
 16  From_Continuing with same job held during university education  362 non-null    int64
 17  From_Other                                                      362 non-null    int64
 18  Factor_Degree                                                   362 non-null    int64
 19  Factor_Class of degree                                          362 non-null    int64
 20  Factor_University Project                                       362 non-null    int64
 21  Factor_Reputation of university                                 362 non-null    int64
 22  Factor_Field of study                                           362 non-null    int64
 23  Factor_Research experience                                      362 non-null    int64
 24  Factor_Personal contacts                                        362 non-null    int64
 25  Factor_Previous work experience                                 362 non-null    int64
 26  Factor_English proficiency                                      362 non-null    int64
 27  Factor_Other professional qualifications                        362 non-null    int64
 28  Factor_Soft skills                                              362 non-null    int64
 29  Factor_Computer literacy                                        362 non-null    int64
 30  Factor_Other                                                    362 non-null    int64
 31  Additional qualifications                                       362 non-null    int64
 32  Completed_Diploma                                               362 non-null    int64
 33  Completed_M-Sc-                                                 362 non-null    int64
 34  Completed_M-Phil-                                               362 non-null    int64
 35  Completed_MBA                                                   362 non-null    int64
 36  Completed_Ph-D-                                                 362 non-null    int64
 37  Completed_LL-B-                                                 362 non-null    int64
 38  Completed_CIMA                                                  362 non-null    int64
 39  Completed_Chartered Accountancy                                 362 non-null    int64
 40  Completed_CMA                                                   362 non-null    int64
 41  Completed_Other                                                 362 non-null    int64
 42  Reading_Diploma                                                 362 non-null    int64
 43  Reading_M-Sc-                                                   362 non-null    int64
 44  Reading_M-Phil-                                                 362 non-null    int64
 45  Reading_MBA                                                     362 non-null    int64
 46  Reading_Ph-D-                                                   362 non-null    int64
 47  Reading_LL-B-                                                   362 non-null    int64
 48  Reading_CIMA                                                    362 non-null    int64
 49  Reading_Chartered Accountancy                                   362 non-null    int64
 50  Reading_CMA                                                     362 non-null    int64
 51  Reading_Other                                                   362 non-null    int64
 52  English_Oral                                                    362 non-null    int64
 53  English_Written                                                 362 non-null    int64
 54  Student Associations                                            362 non-null    int64
 55  Organizing Workshops & Seminars                                 362 non-null    int64
 56  Charities                                                       362 non-null    int64
 57  Sports                                                          362 non-null    int64
 58  Cultural Activities                                             362 non-null    int64
 59  Other                                                           362 non-null    int64
 60  Award/Achievement                                               71 non-null     object
 61  category                                                        362 non-null    object
dtypes: float64(1), int64(52), object(8), period[M](1)
memory usage: 175.5+ KB

manually replace 350th datetime into 2019-05

In [173]:
df.iloc[350, 6]

Period('1905-07', 'M')

In [174]:
df.iloc[350, 6] = pd.Period('2019-05', freq='M')
df.iloc[350, 6]

Period('2019-05', 'M')

In [175]:
df.to_excel('../data/cleaned_data.xlsx', index=False, header=True)